name: Android CI/CD for BookingApp

on:
  push:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (with cache)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'BookingApp/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: BookingApp

      # Rest of steps...
